

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: ml-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount models so we can switch them without rebuilding
      - ./backend/models:/app/backend/models
      # Mount logs so we can see them locally
      - ./backend.log:/app/backend.log
    environment:
      - MODULE_NAME=backend.app
    restart: always
    depends_on:
      - alert-service

  alert-service:
    build:
      context: .
      dockerfile: docker/alert.Dockerfile
    container_name: ml-alert-service
    ports:
      - "8001:8001"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: ml-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always