apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-alert-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-alert-service
  template:
    metadata:
      labels:
        app: ml-alert-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: ml-alert-service
        image: souravmdileep/alert-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: alert-service  # Backend looks for this exact DNS name
spec:
  selector:
    app: ml-alert-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP  # Internal only (Frontend doesn't talk to it directly)
