version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: security-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root  # For development only (Simplifies login)
      VAULT_ADDR: 'http://0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    restart: always
